### ISSUE TITLE
Why use .Net 7.0? it is too high

### ISSUE THREAD

**Issue by httpsColon** [AgitoReiKen/hearthstone-speedhack#2]
Where can I learn a more complete BepInEx_plugin development tutorial?

**Comment by AgitoReiKen** [comment]
You are right, hearthstone uses mscorlib of 4.6. I didn't check that when i was making it.
I will change 7.0 to 4.6 then.
https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/2_plugin_start.html

**Comment by httpsColon** [comment]
> You are right, hearthstone uses mscorlib of 4.6. I didn't check that when i was making it. I will change 7.0 to 4.6 then. https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/2_plugin_start.html

thank you, I resolved some dependency issues and compiled successfully on version 4.8
